### ISSUE TITLE
error: deserialization of generic traits is not supported yet; use #[typetag::serialize] to generate serialization only

### ISSUE THREAD

**Issue by leontiadZen** [dtolnay/typetag#68] opened 2023-09-19 13:46 UTC
I tried to reproduce the pattern in my code, for ser/de but I am getting errors when I try to deserialize :
`error: deserialization of generic traits is not supported yet; use #[typetag::serialize] to generate serialization only`
Is that expected behavior

**Comment by dtolnay** [comment] 2023-09-19 15:29
Duplicate of #1.

**Closed by dtolnay** 2023-09-19 15:29 UTC
